### PR TITLE
Create a new template.html

### PR DESCRIPTION
**Pull request by Tanishqmalu**
A template for a developer

### CODE REVIEW

**Comment by harshagrawal523** [comment]
> Great template , can you fix the font size a bit(it looks too large) if possible , but the overall look of the template is very nice

I will wait for your reply and then will merge!

**Comment by Tanishqmalu** [comment]
Sure, I'll change the font size,but could you highlight any specific area where font needs to be reduced. For the time being i am reducing the fonts of all the headings.

**Comment by codingiitg** [comment]
> Sure, I'll change the font size,but could you highlight any specific area where font needs to be reduced. For the time being i am reducing the fonts of all the headings.

yes you can reduce size from everywhere a bit , rest all is great

**Comment by harshagrawal523** [comment]
> Sure, I'll change the font size,but could you highlight any specific area where font needs to be reduced. For the time being i am reducing the fonts of all the headings.

Did you change?

**Comment by Tanishqmalu** [comment]
Due to some issues, i did not have access to my laptop. I'll do it by tonight.

**Comment by Tanishqmalu** [comment]
Updated. Please check now.

**Comment by harshagrawal523** [comment]
> git pull https://github.com/Tanishqmalu/Portfolyser.git patch-1

cool this is good

**Comment by Tanishqmalu** [comment]
No points for such PRs?

**Comment by harshagrawal523** [comment]
Sorry for the delay in adding points , was not in the city

**Pull request merged**
