### PR TITLE
added appropriate hrefs for login/register

### LINKED ISSUE #3: Login & Register links doesn't work
The Login/Register link on the **homepage** is not working and needs links to be added. Please go through the code to get the appropriate hrefs .

- Please mention the issue name in your PR
- If you have any doubts ask here only.

### PR DESCRIPTION
**Pull request by akshatjain1004**
Resolves #3

### CODE REVIEW

**Comment by harshagrawal523** [comment]
> Resolves #3

The login link is not working. Can you check it once

**Comment by akshatjain1004** [comment]
Hi, can you guide me how exactly should I view the home page

**Comment by harshagrawal523** [comment]
> Hi, can you guide me how exactly should I view the home page

register yourself first by any email id and then login , after that you will be redirected to home page.

**Comment by GunjanDhanuka** [comment]
There have been some changes to the code. Do a `git pull` first and resolve the merge conflicts and then create a PR. If you have any issues, feel free to ask.

**Comment by akshatjain1004** [comment]
Yes, done. Actually I'm not able to run the app. I'm not familiar with the MongoDB URL part. Can you guide me through it?

**Comment by harshagrawal523** [comment]
> Yes, done. Actually I'm not able to run the app. I'm not familiar with the MongoDB URL part. Can you guide me through it?

Hi @akshatjain1004 , you can go through this 
https://www.youtube.com/watch?v=bxsemcrY4gQ&list=PL4cUxeGkcC9jsz4LDYc6kv3ymONOKxwBU&index=9

**Pull request merged**
