### PR TITLE
Update intro.ejs & education.ejs

### LINKED ISSUE #32: Add frontend to Introduction forms page( The theme of the website should be same)
# Description
Provide a clear description of the issue :-
Currently the forms section which takes information about your personal bio and all , it is very basic and has no frontend element.

# Screenshot
Screenshot 2021-12-14 at 22 56 52

# References
`/intro`

### PR DESCRIPTION
**Pull request by ArchismanKarmakar**
## Issue
Fixes #32 #33 

## Description

frontend for /intro

## Type of change
frontend gui

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation change

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] The app runs properly
- [x] I have performed a self-review of my own code
- [x] I have formatted and commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by ArchismanKarmakar** [comment]
#32

**Comment by harshagrawal523** [comment]
> #32

The nav bar is too big when compared to homepage reduce the size of everything a ut and can you but the submit buttons in center.

**Comment by ArchismanKarmakar** [comment]
> > #32
> 
> The nav bar is too big when compared to homepage reduce the size of everything a ut and can you but the submit buttons in center. Try to make the navbar same as homepage and event the font size n all

fixed it sir, actually font size 63% is making other components very small, now changed it 68% for ease  #32 #34

**Comment by harshagrawal523** [comment]
I will review this today

**Comment by ArchismanKarmakar** [comment]
> I will review this today

@harshagrawal523 #32 #33 issues solved/updated.

**Comment by harshagrawal523** [comment]
The navbar is not like other pages it is a bit bigger , please check it once

**Comment by ArchismanKarmakar** [comment]
> sir, actually font size 63% is making other components very small, now changed it 68% for ease

sir, actually font size 63% is making other components very small, now changed it 68% for ease

**Comment by ArchismanKarmakar** [comment]
> The navbar is not like other pages it is a bit bigger , please check it once

i am trying to fix

**Comment by ArchismanKarmakar** [comment]
> The navbar is not like other pages it is a bit bigger , please check it once

i just copied the css and other code from home page only. i am trying to fix it but it's still same

**Comment by ArchismanKarmakar** [comment]
> The navbar is not like other pages it is a bit bigger , please check it once

it is because the bootstrap header and inline css header are clashing, i've updated and fixed everything, please check now.

**Pull request closed without merging**
