### PR TITLE
work and education template added

### PR DESCRIPTION
**Pull request by shmiitg**
Please reivew the pr

### CODE REVIEW

**Comment by harshagrawal523** [comment]
> git pull https://github.com/shmiitg/Portfolyser.git main

it is not showing work and education entires in database

**Comment by harshagrawal523** [comment]
> > git pull https://github.com/shmiitg/Portfolyser.git main
> 
> it is not showing work and education entires in database

did you check this?

**Comment by shmiitg** [comment]
yaah.. it is working fine in my case
Screenshot (270)

**Comment by harshagrawal523** [comment]
> yaah.. it is working fine in my case Screenshot (270)

yes it should show the value we wrote right not "Array"

**Comment by shmiitg** [comment]
actually, i am storing the things inside an array. Like all the companies the user has worked will be there in the array. The order in which the user fills the entries will be there in the array

**Comment by harshagrawal523** [comment]
> actually, i am storing the things inside an array. Like all the companies the user has worked will be there in the array. The order in which the user fills the entries will be there in the array

okay I can see them now , sorry made a mistake

**Comment by shmiitg** [comment]
ok no issues!

**Comment by harshagrawal523** [comment]
> ok no issues!

I just pushed few things and it is showing branch conflicts , can update the code according to it? It wont take much time

**Comment by shmiitg** [comment]
ok I am trying to resolve the conflicts

**Comment by shmiitg** [comment]
Your can check it now

**Comment by harshagrawal523** [comment]
> git pull https://github.com/shmiitg/Portfolyser.git main

Yup it's working! great work

**Comment by harshagrawal523** [comment]
> > git pull https://github.com/shmiitg/Portfolyser.git main
> 
> Yup it's working! great work

#10

**Pull request merged**
