### PR TITLE
Issue 17 dynamic fields

### LINKED ISSUE #17: Issues with the email input in intro
Right now the user can edit the `email` input in `/intro`. Therefore, any user can add intro for some other user if they know their email, which obviously should not happen.
But also, we cannot make `email` input uneditable, because one might want to add another email in the portfolio.

To resolve this issue, make another property in `user.js`, let's say `portfolio_email`.
When POST request is made at `/intro`,  set the value of `email` as the email of the logged-in user, and put the email entered by the user in the form in `portfolio_email`

Make appropriate changes in `final.ejs` too.

### PR DESCRIPTION
**Pull request by letsintegreat**
Changes made in this PR:

 - Removed the hectic iteration over all the documents each time, by making use of [`findOne`](https://mongoosejs.com/docs/api.html#model_Model.findOne)
 - Redirect the user to `/intro` if they try to fetch `/final` before adding an intro
 - If the user goes to `/intro` again after adding the intro once, they will be shown the previously added details. They can edit any detail, and submitting would edit their previous document in the database, instead of adding a new one.
 - Added `project links` component in intro model.
 - Made appropriate changes in final.ejs
 - Now, the user can only change the emails that are to be shown in the portfolio, the actual `user.email` will be added automatically so that users cant add intros for others.
 - Users can add multiple emails and multiple project links by separating them with a comma.

Closes #17 

**Please make sure to drop the `intros` collection in the database, before reviewing the changes, or use an altogether new database.**

### CODE REVIEW

**Comment by letsintegreat** [comment]
Closes #17

**Comment by harshagrawal523** [comment]
> Changes made in this PR:
> 
> * Removed the hectic iteration over all the documents each time, by making use of [`findOne`](https://mongoosejs.com/docs/api.html#model_Model.findOne)
> * Redirect the user to `/intro` if they try to fetch `/final` before adding an intro
> * If the user goes to `/intro` again after adding the intro once, they will be shown the previously added details. They can edit any detail, and submitting would edit their previous document in the database, instead of adding a new one.
> * Added `project links` component in intro model.
> * Made appropriate changes in final.ejs
> * Now, the user can only change the emails that are to be shown in the portfolio, the actual `user.email` will be added automatically so that users cant add intros for others.
> * Users can add multiple emails and multiple project links by separating them with a comma.
> 
> Closes #17
> 
> **Please make sure to drop the `intros` collection in the database, before reviewing the changes, or use an altogether new database.**

this is working but only when the user is added manually , if I login from google it is not working , can you check it once if it's working when you are using login in with google

**Comment by letsintegreat** [comment]
Oh, I forgot to test with a google user, please wait.

**Comment by letsintegreat** [comment]
@harshagrawal523 It is working fine with google sign-in as well. Can you elaborate on exactly which part failed to work as expected in the case of google sign-in?

**Comment by harshagrawal523** [comment]
> @harshagrawal523 It is working fine with google sign-in as well. Can you elaborate on exactly which part failed to work as expected in the case of google sign-in?

After I login with google , if I enter my details and then I type `/final` it redirects me to `/intro` again , and there all fields are empty

**Comment by letsintegreat** [comment]
@harshagrawal523 Make sure to press submit after entering your details in `/intro`.

**Comment by harshagrawal523** [comment]
> @harshagrawal523 Make sure to press save after entering your details in `/intro`.

@letsintegreat I have texted you on discord please check once

**Pull request merged**
